gText_Birch_Welcome::
	.string "Γεια! Συγγνώμη για την αναμονή!\p"
	.string "Καλώς ήρθες στον κόσμο των POKéMON!\p"
	.string "Το όνομά μου είναι BIRCH.\p"
	.string "Αλλά όλοι με φωνάζουν ΚΑΘΗΓΗΤΗ\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Αυτό εδώ είναι που αποκαλούμε\l"
	.string "“POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ο κόσμος κατοικείται ευρέως από\n"
	.string "πλάσματα γνωστά ως POKéMON.\p"
	.string "Εμείς οι άνθρωποι ζούμε μαζί με τα\n"
	.string "POKéMON, άλλοτε σαν σύντροφοι,\l"
	.string "και άλλοτε σαν συνεργάτες.\p"
	.string "Και μερικές φορές, ερχόμαστε μαζί\n"
	.string "και κάνουμε μάχες με ομοίους μας.\p"
	.string "Αλλά παρά την εγγύτητά μας, δεν\n"
	.string "γνωρίζουμε τα πάντα για τα POKéMON.\p"
	.string "Η αλήθεια είναι πως υπάρχουν πολλά,\n"
	.string "πολλά μυστικά γύρω από τα POKéMON.\p"
	.string "Για να αποκαλύψω τα μυστήρια των\n"
	.string "POKéMON, έχω αναλάβει έρευνα.\l"
	.string "Αυτό ακριβώς κάνω.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Κι εσύ ποιος είσαι;$"

gText_Birch_BoyOrGirl::
	.string "Είσαι αγόρι;\n"
	.string "Ή είσαι κορίτσι;$"

gText_Birch_WhatsYourName::
	.string "Μάλιστα.\n"
	.string "Πώς σε λένε;$"

gText_Birch_SoItsPlayer::
	.string "Ώστε σε λένε {PLAYER}{KUN};$"

gText_Birch_YourePlayer::
	.string "Α, εντάξει!\p"
	.string "Είσαι {PLAYER_ART_LOWER} {PLAYER}{KUN}, και μετακομίζεις\n"
	.string "στο LITTLEROOT, όπου και μένω.\l"
	.string "Κατάλαβα τώρα!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Εντάξει, είσαι έτοιμ{PLAYER_ADJ};\p"
	.string "Η ολόδική σου περιπέτεια πρόκειται\n"
	.string "να ανοιχτεί μπροστά σου.\p"
	.string "Πάρε θάρρος, και κάνε άλμα στον\n"
	.string "κόσμο των POKéMON, όπου όνειρα,\l"
	.string "περιπέτειες, και φιλίες σε περιμένουν!\p"
	.string "Λοιπόν, θα σε δω αργότερα.\n"
	.string "Θα με βρεις στο ΕΡΓΑΣΤΗΡΙΟ POKéMON.\p"
	.string "$"
