Text_BootUpPC:
	.string "{PLAYER_ART} {PLAYER} άνοιξε το PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Με ποιο PC θα ήθελες να συνδεθείς;$"

gText_AccessedSomeonesPC::
	.string "Συνδέθηκες με το PC ΚΑΠΟΙΟΥ.$"

gText_StorageSystemOpened::
	.string "Το Σύστημα Αποθήκευσης POKéMON άνοιξε.$"

gText_AccessedPlayersPC::
	.string "Συνδέθηκες με το PC Τ{PLAYER_GEN_CAP} {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Συνδέθηκες με το PC ΤΗΣ LANETTE.$"
