gText_PkmnTransferredSomeonesPC::
	.string "Το {STR_VAR_2} μεταφέρθηκε στο\n"
	.string "PC ΚΑΠΟΙΟΥ.\p"
	.string "Τοποθετήθηκε στο \n"
	.string "ΚΟΥΤΙ “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "Το {STR_VAR_2} μεταφέρθηκε στο\n"
	.string "PC ΤΗΣ LANETTE.\p"
	.string "Τοποθετήθηκε στο \n"
	.string "ΚΟΥΤΙ “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "Το ΚΟΥΤΙ “{STR_VAR_3}” στο\n"
	.string "PC ΚΑΠΟΙΟΥ ήταν γεμάτο.\p"
	.string "Το {STR_VAR_2} μεταφέρθηκε στο\n"
	.string "ΚΟΥΤΙ “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "Το ΚΟΥΤΙ “{STR_VAR_3}” στο\n"
	.string "PC ΤΗΣ LANETTE ήταν γεμάτο.\p"
	.string "Το {STR_VAR_2} μεταφέρθηκε στο\n"
	.string "ΚΟΥΤΙ “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "Δεν υπάρχει άλλος χώρος για POKéMON!\p"
	.string "Τα ΚΟΥΤΙΑ POKéMON είναι γεμάτα και\n"
	.string "δεν δέχονται άλλα!$"

gText_NicknameThisPokemon::
	.string "Θέλεις να δώσεις παρατσούκλι\n"
	.string "στο {STR_VAR_1};$"
