gText_WouldYouLikeToRestYourPkmn::
	.string "Γεια σας, και καλώς ήρθατε\n"
	.string "στο ΚΕΝΤΡΟ POKéMON.\p"
	.string "Επαναφέρουμε τα κουρασμένα σας\n"
	.string "POKéMON σε πλήρη υγεία.\p"
	.string "Θα θέλατε να αναρρώσετε τα POKéMON σας;$"

gText_IllTakeYourPkmn::
	.string "Εντάξει, θα πάρω τα POKéMON\n"
	.string "σας για λίγα δευτερόλεπτα.$"

gText_RestoredPkmnToFullHealth::
	.string "Σας ευχαριστώ για την αναμονή.\p"
	.string "Επαναφέραμε τα POKéMON σας\n"
	.string "σε πλήρη υγεία.$"

gText_WeHopeToSeeYouAgain::
	.string "Ελπίζουμε να σας ξαναδούμε!$"

gText_WelcomeCutShort::
	.string "Γεια σας, και καλώς ήρθατε\n"
	.string "στο ΚΕΝΤΡΟ POKéMON.\p"
	.string "Επαναφέρουμε τα κουρασμένα σας\n"
	.string "POKéMON σε πλήρη υγεία.\p"
	.string "Θα θέλατε να …$"

gText_NoticesGoldCard::
	.string "Α-Αυτή η κάρτα…\n"
	.string "Μήπως είναι… η ΧΡΥΣΗ ΚΑΡΤΑ;!\p"
	.string "Ω, το χρυσό της χρώμα είναι θαυμάσιο!\n"
	.string "Τα τέσσερα αστέρια αστράφτουν λαμπρά!\p"
	.string "Έχω δει πολλούς ΕΚΠΑΙΔΕΥΤΕΣ με\n"
	.string "ΑΣΗΜΕΝΙΑ ΚΑΡΤΑ, αλλά, {PLAYER},\l"
	.string "είσαι {PLAYER_ART_LOWER} πρώτ{PLAYER_ADJ} {TRAINER} που έχω\l"
	.string "δει με ΧΡΥΣΗ ΚΑΡΤΑ!\p"
	.string "Εντάξει, {PLAYER}, δώσε μου παρακαλώ\n"
	.string "την τιμή να αναρρώσω τα POKéMON σου!$"

gText_YouWantTheUsual::
	.string "Χαίρομαι που σε βλέπω, {PLAYER}!\n"
	.string "Θες το συνηθισμένο, σωστά;$"

gText_IllTakeYourPkmn2::
	.string "Εντάξει, θα πάρω τα POKéMON\n"
	.string "σου για λίγα δευτερόλεπτα.$"

gText_ThankYouForWaiting::
	.string "Σε ευχαριστώ για την αναμονή.$"

gText_WeHopeToSeeYouAgain2::
	.string "Ελπίζω να σε ξαναδώ!$"
