	.align 2
gText_ConfirmSave::
	.string "Θέλεις να σώσεις το παιχνίδι;$"

gText_AlreadySavedFile::
	.string "Υπάρχει ήδη αποθηκευμένο αρχείο.\n"
	.string "Να αντικατασταθεί;$"

gText_SavingDontTurnOff::
	.string "ΑΠΟΘΗΚΕΥΣΗ…\n"
	.string "ΜΗΝ ΚΛΕΙΣΕΙΣ ΤΗΝ ΚΟΝΣΟΛΑ.$"

gText_PlayerSavedGame::
	.string "{PLAYER_ART} {PLAYER} έσωσε το παιχνίδι.$"

gText_DifferentSaveFile::
	.string "ΠΡΟΣΟΧΗ!\p"
	.string "Υπάρχει αποθηκευμένο αρχείο\n"
	.string "από άλλο παιχνίδι.\p"
	.string "Αν σώσεις τώρα, η περιπέτεια του\n"
	.string "άλλου αρχείου, μαζί με τα αντικείμενα\l"
	.string "και POKéMON του, θα χαθούν ολοκληρωτικά.\p"
	.string "Είσαι σίγουρ{PLAYER_ADJ} πως θέλεις να\n"
	.string "αντικαταστήσεις το άλλο αρχείο;$"

gText_SaveError::
	.string "Σφάλμα αποθήκευσης.\p"
	.string "Παρακαλώ αλλάξτε την\n"
	.string "εναλλακτική μνήμη.$"

gText_SavingDontTurnOffPower::
	.string "ΑΠΟΘΗΚΕΥΣΗ…\n"
	.string "ΜΗΝ ΚΛΕΙΣΕΙΣ ΤΗΝ ΚΟΝΣΟΛΑ.$"
